### ISSUE TITLE
Can't install on ubunto16.04

### ISSUE THREAD

**Issue by xins0123** [xtuple/xtuple-admin-utility#127]
when I execute ./xtuple-utility.sh -a, occurs error:
make: Leaving directory '/opt/xtuple/4.10.1/xtuple-web/xtuple/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
npm WARN engine escodegen@1.9.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine request@2.83.0: wanted: {"node":">= 4"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine request-promise-native@1.0.5: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine esprima@3.1.3: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine har-validator@5.0.3: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine form-data@2.3.1: wanted: {"node":">= 0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine punycode@2.1.0: wanted: {"node":">=6"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine cryptiles@3.1.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine sntp@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine hoek@4.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine boom@4.3.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine boom@5.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'parse5'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.10.0-28-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /opt/xtuple/4.10.1/xtuple-web/xtuple
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0

...

11:26:46 xtuple >> Creating systemd service unit using filename /etc/systemd/system/xtuple-xtuple-web.service

/etc/xtuple/4.10.1/xtuple-web/config.js:30
      port: ,
            ^
<<ERROR 2017-12-26T03:26:46.343Z>> Unrecoverable exception. Unexpected token ,SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at exports.build (/opt/xtuple/4.10.1/xtuple-web/xtuple/scripts/lib/build_all.js:123:16)
    at /opt/xtuple/4.10.1/xtuple-web/xtuple/scripts/build_app.js:35:3
    at Object.<anonymous> (/opt/xtuple/4.10.1/xtuple-web/xtuple/scripts/build_app.js:55:2)
    at Module._compile (module.js:456:26)
11:26:46 xtuple >> All set! You should now be able to log on to this server at https://172.16.16.41: with username admin and password admin. Make sure you change your password!

**Comment by gilmoskowitz** [comment]
Fixed by #129
