### ISSUE TITLE
user:pass method to clone github xtuple private-extensions

### ISSUE THREAD

**Issue by xtpclark** [xtuple/xtuple-admin-utility#20]
https://username:password@github.com/username/repository.git

...Don't log it, prompt when asked?

**Comment by davidbeauchamp** [comment]
if we use https://blah it will default to prompting. This works just fine as long as you don't have two-factor authentication enabled

**Comment by xtpclark** [comment]
prompting would be cool. I just hate setting up the SSH keys on all the boxes I might use this on...
