### ISSUE TITLE
Allow freeform selection of release version

### ISSUE THREAD

**Issue by bixwilson** [xtuple/xtuple-admin-utility#27]
Would it be possible to have an option to type in an arbitrary release or tag? After I provision a new cluster I want to install the 490rc demo database.
1. Choose 3-Database Maintenance
2. Set database info to my new cluster
3. Select 11-Download Specific Database
4. enter the filename (I typed bc_490rc_demo)
5. On the Choose Version screen I'd like an option for "Other" where I can manually enter the version tag.

**Comment by xtpclark** [comment]
There's a couple of similar versions of things like this that we 'need'. Support for custom branches. Right now we use git lsremote --tags.  This shows our tagged releases. --heads would show the 'other' things i.e. 4_9_x .  The "Other" for manually entering the version should support 4_9_x and v4.9.0 conventions

**Comment by xtpclark** [comment]
Support for development -heads and -tags is working.

**Comment by bixwilson** [comment]
Need to update config.js and restart xtuple after restoring downloaded db.
