### ISSUE TITLE
Sometimes eth0 doesn't exist.. :

### ISSUE THREAD

**Issue by xtpclark** [xtuple/xtuple-admin-utility#32]
Sometimes the Network interface is something other than eth...

<pre>
start: Job is already running: xtuple-test49x
Device "eth0" does not exist.
21:35:06 xtuple >> All set! You should now be able to log on to this server at https://:8443 with username admin and password admin. Make sure you change your password!
21:38:19 xtuple >> Exiting xTuple Admin Utility
ubuntu@test:~/xtuple-utility$ ifconfig
em1       Link encap:Ethernet  HWaddr 40:a8:f0:1f:64:48  
          inet addr:192.168.2.153  Bcast:192.168.2.255  Mask:255.255.255.0
</pre>

**Comment by davidbeauchamp** [comment]
I knew this day would come : https://github.com/davidbeauchamp/xtuple-utility/blob/master/mobileclient.sh#L240
