### ISSUE TITLE
Rename database does not update web login config

### ISSUE THREAD

**Issue by bixwilson** [xtuple/xtuple-admin-utility#34]
If you use the rename database function to change the name of a database, is must also update the config.js file for the associated website. Otherwise you will no longer be able to log in to that db from the web client.

file location (for my current test setup): 
`/etc/xtuple/4.8.1/test_install_481/config.js`

location in file: 
```//Add each database to the array.
databases: ["demo","quickstart","etc"],
testDatabase: ""```

**Comment by davidbeauchamp** [comment]
If this is done it should prompt first, we can't assume the database being renamed is mobilized or that the administrator wants config.js to be updated (say if they are renaming a database in preparation to restore one in its place)

**Comment by bixwilson** [comment]
Very good point. Yes it should. Also need to `service xtuple-whatever restart` after the config.js is updated.
