### ISSUE TITLE
Carve Pilot from database not working

### ISSUE THREAD

**Issue by bixwilson** [xtuple/xtuple-admin-utility#35]
I attempted to use this command on my test system and got an unhelpful failure message: 

>MessageBox >> Something has gone wrong. Check output and correct any issues.

Not sure what output to check. The log file showed the same message as above with no additional info.

**Comment by elipup** [comment]
The actual error is coming from the postgres command:
```bash
sudo su - postgres -c "psql postgres -q -h $PGHOST -p $PGPORT -c \"CREATE DATABASE \"$PILOT\" TEMPLATE \"$SOURCE\" OWNER admin;\""
```
When I tested carving a pilot, I got this in my terminal (but not in the log):
> ERROR:  source database "demo481" is being accessed by other users
> DETAIL:  There are 2 other sessions using the database.

Then I ran this query to see who's connected:
```sql
SELECT datname, usename, state, query FROM pg_stat_activity;
```

> demo481  | admin    | idle   | LISTEN nodext
> demo481  | admin    | idle   | select xt.get($${"nameSpace":"SYS","type":"SessionStore","username":"node","encryptionKey":"kbOXTzQ_QMbxb2i+&kV1h^xj$O9m6SqzV98b08B4fypjJhO3L3l4dUbfZ1L+!sZ-"}$$) as request
> postgres | postgres | active | SELECT datname, usename, state, query FROM pg_stat_activity;

I did install the mobile client during a previous testing run and it looks like the server is holding on to some connections.  How to we want to handle this situation?

**Comment by davidbeauchamp** [comment]
xtuple-server would just kill every pid connected to the database when you chose to carve a pilot. We should probably prompt before doing that, or refuse to attempt it if we detect connected users. 

Alternatively, we could attempt the template method first as we are doing, and if it fails ask if we want to use the traditional method of making a manual backup and restoring it to the db.

**Comment by davidbeauchamp** [comment]
Also, we should check what commands aren't being log_exec'd

**Comment by gilmoskowitz** [comment]
syntax note: everything might be easier if the `psql` were run with `-U postgres` instead of `sudo su ...`
