### ISSUE TITLE
Create database from file command does not update config.js

### ISSUE THREAD

**Issue by bixwilson** [xtuple/xtuple-admin-utility#36]
When you create any new database in a cluster the app should prompt to ask if we want to make that db available via the web client. If user says yes, then modify config.js and restart the xtuple process.

**Comment by zrichmond** [comment]
Looks like this was removed for some reason.  I'd be nice to have back in there.  I tried it on the current master, and the config.js change still worked, but looks like some strangeness on restarting the service. (Sorry for commenting on a closed issue, but I figured it's better than duplicating)

**Comment by davidbeauchamp** [comment]
This may be revisited at some point, but I wanted to make sure I keep steps separate, and the prompt every time you do this was getting to me. What I envision is a menu entry to select a database and add it to config.js when you decide you want to. 

Just adding a database to config.js is not enough, you still need to build_app on that database once its there and that part wasn't being done. 

Regarding the service restarting, have not had any issues with this on my setup. If you can log any errors or anything please open a new issue.
