### ISSUE TITLE
Upgrade xTuple Database does not work

### ISSUE THREAD

**Issue by bixwilson** [xtuple/xtuple-admin-utility#38]
This command currently does nothing, as far as I can tell.

**Comment by davidbeauchamp** [comment]
You would be correct, it does nothing right now as we don't have the infrastructure in place to support it. I did write an API to provide a way to determine upgrade path (meaning, Im on 3.7.4 and want to go to 4.8.1 how do I do it), but we need to modify the Updater to support headless mode.
