### ISSUE TITLE
Restore database from file generates js function error

### ISSUE THREAD

**Issue by bixwilson** [xtuple/xtuple-admin-utility#39]
Error occurred, WARNING: failed to find js function function "xt.js_init" does not exist. could not find js_init.js.

**Comment by elipup** [comment]
I see that when restoring as well.  It's coming from the pg_restore command.  The function name originally appears here https://github.com/xtuple/xtuple-admin-utility/blob/master/postgresql.sh#L324

```log "Adding plv8.start_proc='xt.js_init' to postgresql.conf"```

It looks like it can be safely ignored, but I'm not too sure on why it pops up in the first place.

**Comment by bendiy** [comment]
This is an expected and benign `WARNING` that is the result of adding `plv8.start_proc='xt.js_init'` to postgresql.conf.

One unfortunate result from this setting is that anytime ANY `plv8` function is ran, the `xt.js_init()` function will also be called. This even happens on an empty database with just the `plv8` extension installed.

In our case, [we are installing/running a few `plv8` functions](https://github.com/xtuple/xtuple/blob/4_10_x/foundation-database/manifest.js#L18-L22) before `xt.js_init()` exists in the database. Which causes this: `WARNING: failed to find js function function "xt.js_init" does not exist. could not find js_init.js.`

Something we might consider doing in the future is using a core function for the `plv8.start_proc` setting like `current_database()`, so it will always exist. Then modify it to also call our `plv8` init function. `plv8.start_proc` is considered best practice to initialize the JavaScript environment. It also has this side effect.

**Comment by gilmoskowitz** [comment]
Generally I agree with @bendiy - calling a function that we know exists would reduce the noise. It should be one of our functions so we can include the right hooks regardless of whether the database is mobilized or not. We should also be careful in choosing the function to call so it's clear that there may be side-effects when calling it.

**Comment by bendiy** [comment]
The benefit of a core function is it will always be available. We could override it like this for any xTuple database install.
```
CREATE OR REPLACE FUNCTION current_database()
  RETURNS name AS
$BODY$
BEGIN
PERFORM xt.js_init();

RETURN 'current_database';
END;
$BODY$
  LANGUAGE plpgsql STABLE STRICT
  COST 1;
```

Then set `plv8.start_proc='current_database'` and you will not get an error on xtuple and non-xtuple databases that might share the same server and have plv8 functions.

The other option would be to do this in `login()` or something similar, but non-xtuple databases will not have that function or may have their own `login()` that's not safe to call all the time. A function like `current_database()` should be safe to call and exists on all databases. The downsides:
1. Hacking a core function
2. Performance impact to normal uses of `current_database()`

**Comment by gilmoskowitz** [comment]
[Hacking a core function](https://github.com/xtuple/xtuple/blob/164a792a3dd1e35af49a8900501c8e2d999ed578/database/source/xt/functions/pg_advisory_unlock.sql) is evil.

**Comment by elipup** [comment]
I will add a change to the utility to display the pg_restore output to the user. This will at least be easier for the user to deal with.
