### ISSUE TITLE
This tool vs xtuple-server

### ISSUE THREAD

**Issue by joelwhrs** [xtuple/xtuple-admin-utility#51]
I was away from the xTuple scene for a bit and when getting back on github I noticed this tool. It sounds very similar to what xTuple-Server does. Is this meant to completely replace xTuple-Server or where does this tool fit?

**Comment by gilmoskowitz** [comment]
@joelwhrs - Yes, yes, and read on.

xtuple-admin-utility is similar in purpose and functionality to xtuple-server-core + xtuple-server. There are a few important differences:

- Fewer external code dependencies. Written primarily in bash, xtuple-admin-utility requires less infrastructure to run.
- Finer control over activity. xtuple-server encoded some ideas on the ideal way to configure and run the full xTuple technology stack. In practice, though, there are times when we need to step in and do some things manually.
- Reduced reliance on the Internet. xtuple-server required reliable Internet connectivity. Real-world experience taught us this is unrealistic.

We will retire xtuple-server when xtuple-admin-utility matches or exceeds the capabilities of xtuple-server. Please give it a try and let us know what you think.

**Comment by joelwhrs** [comment]
Perfect. I will throw it on a VM and try it out. Thanks!
