### ISSUE TITLE
On mobile client screen, make the Instance Name more informative

### ISSUE THREAD

**Issue by xtpclark** [xtuple/xtuple-admin-utility#53]
The path that is created by /opt/xtuple/VERSION/INSTANCENAME should describe what this name is for - The xtuple mobile web client source code.  It can be confusing.
Also, this becomes part of the service script name - That would be useful to know.

**Comment by elipup** [comment]
Would it be enough to inform the user of this when they enter the instance name? I feel like this should be on the wiki.
