### ISSUE TITLE
NGINX Setup - More descriptive

### ISSUE THREAD

**Issue by xtpclark** [xtuple/xtuple-admin-utility#54]
Screen says Hostname.  Would be nice to have more description on what this is for.  Also, state what part of the FQDN you are constructing, OR - just combine the HOSTNAME and DOMAIN NAME screens together and call it Enter FQDN.

**Comment by davidbeauchamp** [comment]
Fixed by https://github.com/xtuple/xtuple-admin-utility/pull/59
