### ISSUE TITLE
Inconsistent Menu Navigation

### ISSUE THREAD

**Issue by zrichmond** [xtuple/xtuple-admin-utility#56]
Just starting to work with the utility.  In some ways I am liking it, in others it's a bit rough around the edges (hence the alpha status I assume).  I'll post more as I work with it more. 

Anyhow the point of the issue, and please excuse the duplicate if there are  it would be nice to fix a few of the inconsistencies of the navigation.

 * Every menu should allow one to back out via Esc key
 * Top level menu  Esc key exits, but this should be labeled as an exit (maybe an are you sure? check)
 * Might be good to have Esc noted as a back key.
 * Should be able to have Back (esc) Continue (Enter), Cancel ( maybe only selectable via arrow keys?)
 * Some menus require right-arrow key to get to the bottom navigation, which is a bit confusing.
 * Sometimes cancel exits completely, this should say Exit not cancel.
 
The main time this caused me a problem was when I was doing the initial install, and when prompted for the hostname I had entered the full domain name per the xtuple-server tool convention, but the next screen asked for the domain name.  So, I cancelled.  Oops...  Then I was left with an undermined state of setup.  Which on one hand has been good for me to figure out all various options.

Anyhow, nice job it's definitely looking better for general use than the previous bootstrap method. Also, knowing how hard it can be to throw out previous work to start over, I really appreciate that you all do in order to make xtuple great.

**Comment by zrichmond** [comment]
I am liking this new utility and new way of setting up the server.  I know it's a bit vague, but the menu strangeness seems to be mostly in the Database Maintenance option.  At one point hitting the escape key generated:

```
ERROR:  syntax error at or near ";"
LINE 1: DROP DATABASE ;
```
Under the rename, when I wanted to cancel I got:

```
ALTER DATABASE ihsco_481_dev RENAME TO ;
```

So I guess since there is the cancel option reachable via arrow keys it might work to just ignore the escape key generally?

Sorry, I'm not trying to break it, it's just hitting the escape key is so natural when using a command line utility it should probably fail gracefully.

**Comment by zrichmond** [comment]
Noticed that #54 covers the hostname/domain name quirk.

**Comment by zrichmond** [comment]
I guess I've been kind of playing with this a bit, since I'd rather be doing things the new way than sticking with the old.

Here's a concrete reproducible one :

PostgreSQL Maintenance -> Remove PostgresSQL 9.3 -> Uninstall PostgreSQL 9.3? ...  

Hit <Esc> out of habit.... Uninstall still happens.

**Comment by davidbeauchamp** [comment]
I agree with your points, each menu is a new instance of whiptail basically, which draws the menu and gives the back either as a return code or capturing stdout into a bash variable. I did some testing just now and whiptail exits with with code 255 when you hit escape. Currently the question menus are using an if block, [like your example issue](https://github.com/xtuple/xtuple-admin-utility/blob/master/postgresql.sh#L171-L172), which aren't doing a great job of capturing codes other than 0 and 1. 

The way it stands there is a cancel or return to previous menu option as the last choice in any of the menus. I will play with whiptail a bit more to see if I can make the bottom select/exit options flow between the menus a bit more smoothly. There are already a couple instances where I swapped yes/no around to make the default choice be No, which means I have to invert the conditional logic below it (see same link as above.. "--yes-button "No""...), but hadn't come across such a strong Escape habit yet hah. At least not since [Intermail's](http://textfiles.com/computers/DOCUMENTATION/iminfo.txt) "Press ESC twice to access the BBS..." message

**Comment by davidbeauchamp** [comment]
Just realized that it is because of the swapped yes/no that causes escape to misfire, if I didn't invert the logic, you hitting escape would run the actual "no" code and would return to the calling function instead of continuing on to uninstall..

**Comment by davidbeauchamp** [comment]
Please check out my branch here: https://github.com/davidbeauchamp/xtuple-admin-utility/tree/navigationWork and test out the changes to the PostgreSQL maintenance menu, using it as an example of how I felt the flow could work. Basically, anything except selecting a valid option will take you back to where you were. Escaping out of the PostgreSQL menu will take you to the main menu, where escaping yet again will exit the utility all together. Please test out that menu and let me know if that flows a bit better for you. 

Thank you very much for your feedback, don't worry about breaking anything -- this is exactly the kind of feedback we are looking for and appreciate you hammering on it.

**Comment by davidbeauchamp** [comment]
That branch now has an overhaul of the entire menu structures interaction with parent/child menus. Give it a whirl and let me know what you think. 

I left the bottom menu entries in for now (the ones that say "Return to ... menu"), however the default behavior for any menu is to return to the menu that called it. The only menu entry that exits now is the main menu, and its the only one labled as Exit, the rest now say cancel. I think this means I can remove the bottom menu entries for "Return to .. menu" but I will wait and test more. 

Regarding the select/cancel buttons, the way to get to them usually is to tab out of the menu (or for select, just hit enter on the menu entry you chose). You can use the right arrow, it effectively does the same thing as tab.

**Comment by zrichmond** [comment]
Couple of seemingly minor bugs,

Uninstall Web Client: 
```
logging.sh: line 19: remove_mwc: command not found
```

Also looks like #54 is handled but:

Install nginx -> Host name -> Domain name <Cancel/Esc>  

Reentering Install nginx the host name is skipped since it is already set, of course exiting completely does reset.

Definitely much improved, overall it feels like one utility and allows for easy consistent navigation now.  Thanks!

**Comment by davidbeauchamp** [comment]
Uninstalling the web client is current not a supported path, though we have some methods worked up they require quite a bit more testing. I should make that menu entry display a message box telling the user of such. 

Good point on the nginx path.. I could unset those variables once nginx is done installing, they don't need to be kept around for anything. 

Thank you for testing.

**Comment by davidbeauchamp** [comment]
Fixed by https://github.com/xtuple/xtuple-admin-utility/pull/59
