### ISSUE TITLE
Initial Install Fails

### ISSUE THREAD

**Issue by zrichmond** [xtuple/xtuple-admin-utility#60]
So far I have not been able to successfully install via the instructions on the wiki. Neither command-line nor interactive seem to work. I have tried multiple times with fresh installs of ubuntu 14.04.3.  Each time something hangs and I have to force quit. 

```
<snip>
17:52:37 xtuple >> MessageBox >> Password for user postgres successfully reset
17:52:40 xtuple >> Downloading http://files.xtuple.org/common/init.sql to file /home/zak/xtuple-admin-utility/init.sql using axel console output only
^C18:01:02 xtuple >> Breaking due to user CTRL-C
18:01:02 xtuple >> Exiting xTuple Admin Utility
```

I've waited longer other times.

Using the interactive menu, I am able to get a working install eventually.  It's a little bit tricky because the admin user isn't created before the hanging.

**Comment by davidbeauchamp** [comment]
Does http://files.xtuple.org/common/ open for you using a browser?

What about this command from the command line?
axel -n 5 "http://files.xtuple.org/common/init.sql" -o init.sql

**Comment by zrichmond** [comment]
I thought the same thing when it was happening, and at the time I logged in with another terminal, used wget to make sure the box could download the file, which it could.

**Comment by davidbeauchamp** [comment]
What about using axel (not wget)? I've been using it since its a nice way to multithread downloads, but it may be causing your issue depending on firewall settings. wget may be enough (the largest thing currently downloaded is the database backup and those are ~10MB..)

**Comment by zrichmond** [comment]
Fresh VM  running:
```
./xtuple-utility.sh -a -d demo481 -p 9.3 -x 4.8.1
```
like I had been running and failing Sat. but now is building the web client.

The only difference is that I am now on my network at the office where I have the firewall is even more restrictive.  Network at home seemed to be working fine throughout the problems (cable modem, but streaming other traffic was fine).

So likely network problem.  I guess the bigger issue is how to recover from network problems during the install.

One thing that may have helped me in recovering, would be to add the ability to create the admin user as well as reset the password from the utility.  However, I'd guess that's just one issue that could arise from network problems during install, it's just strange that it was in the same stage for me (sometimes it had stopped at extras.sql)

FYI it's installed now and working just fine via web client on the demo481 db.

**Comment by davidbeauchamp** [comment]
It isn't quite labeled as such, but "Prepare cluster for xTuple" under the PostgreSQL menu loads extras.sql and init.sql into the selected database cluster (which creates the admin users). Also, on the PostgreSQL menu there is a "Reset passwords" options lets you change postgres and admin user passwords. 

As far as recovering from network issues, once things stabilize a bit as far as features/process goes, I would like to create a global "you are here" map, sort of a "I failed here, at step 4 which is "foo", your next steps would be "bar".

**Comment by zrichmond** [comment]
I found the reset passwords, but knowing that prepare cluster is where it stopped, sounds like that would be the place to start for fixing it.  I'll give it a try since I have a few VMs in various stages of install.

Network issues aside, for now I should just chalk it up to "Shouldn't be working at home on a Sat"  Anyway feel free to quote the "xTuple Admin Utility v0.1Alpha" version status and we're working on the documentation anytime.

Thanks!

**Comment by davidbeauchamp** [comment]
This may be a bit helpful, [here are the steps](https://github.com/xtuple/xtuple-admin-utility/blob/master/xtuple-utility.sh#L142-L153) that the utility does when installing the complete stack. Each one is a function defined in one of the various files, like database.sh and postgresql.sh.
