### ISSUE TITLE
Installing prerequisites fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by saierd** [xtuple/xtuple-admin-utility#64]
When trying to install with `./xtuple-utility.sh -a` on a clean Ubuntu 14.04 Server, I got the message

    Something went wrong installing prerequisites for ubuntu/trusty. Check the log for more info.

I couldn't read the `apt-get` error message, but I believe this happened because your script set up the PostgreSQL repository, but skipped the `apt-get update` afterwards (see [this part of your script](https://github.com/xtuple/xtuple-admin-utility/blob/master/common.sh#L94-L100)).

It worked after I manually ran the `apt-get update`.

**Comment by davidbeauchamp** [comment]
Thank you for pointing this out, I have been fiddling with the proper way to detect when apt-get update ran last but it seems I haven't quite nailed it.

**Comment by davidbeauchamp** [comment]
Fixed by https://github.com/xtuple/xtuple-admin-utility/commit/f0bf22dfcf424f8d23c1296e410a6f6185aa94c1
