### ISSUE TITLE
Can't connect to external db unless postgresql is provisioned locally

### ISSUE THREAD

**Issue by teemumag** [xtuple/xtuple-admin-utility#70]
xtuple-admin does not seem to install postgresql client. In a fresh machine, I had to provision postgresql server locally before I was able to setup a web client for a remote server.

**Comment by davidbeauchamp** [comment]
The initial execution of xtuple-utility.sh should install the PostgreSQL client, [Here is the line for Ubuntu](https://github.com/xtuple/xtuple-admin-utility/blob/master/common.sh#L96). 

Currently xTuple admin utility is written to manage the local server, in what way were you trying to deploy a remote web client?
