### ISSUE TITLE
admin user not being created when provisioning database

### ISSUE THREAD

**Issue by TonyCan** [xtuple/xtuple-admin-utility#77]
Looks like you left out a " on line 285 of database.sh (i.e. current code OWNER admin" needs to be changed to OWNER "admin").  This is causing provisioning errors.

Not a developer, so I may be mistaken...

**Comment by elipup** [comment]
If you are referring to
`log_exec psql -h $PGHOST -p $PGPORT -U $PGUSER -d postgres -q -c "CREATE DATABASE "$DEST" OWNER admin"`
then the quotations are correct as is.

If you are seeing errors, please post them here.
