### ISSUE TITLE
xDruple: Do not do anything special for DEPLOYER_NAME.  Just use regular xtuple user.

### ISSUE THREAD

**Issue by xtpclark** [xtuple/xtuple-admin-utility#88]
I don't think we should use the DEPLOYER stuff.
# DEPLOYER NAME SHOULD JUST BE DEFAULT xtuple

```
log_exec sudo chown -R ${DEPLOYER_NAME}:${DEPLOYER_NAME} /home/${DEPLOYER_NAME}/.composer
```

**Comment by gilmoskowitz** [comment]
We need to keep `DEPLOYER_NAME` because xTAU creates some directories as root and then needs to `chown` them. Other than that, use of it seems pretty limited.
