### ISSUE TITLE
XTAU and Mobile

### ISSUE THREAD

**Issue by tomdatkins** [xtuple/xtuple-admin-utility#98]
Some of the menu's are a little confusing for customers who would like to manage the updates themselves. If you have E commerce package, you need to have "Mobile" installed, but since that is going away, the menu's are a little miss leading.

I would like to rename some of the menu;s to better reflect the current processes.

5. Web Client Maintenance, i would like to change to something like "xTuple Server Maintenance"

and the sub menu:
1. Install xTuple Web Client, I would like to change to something like "Tuple Server Install/update", to better reflect what it's doing.

**Comment by bixwilson** [comment]
Moving this to dogfood.
